[package]
description = "An experimental Tauri Plugin for Sentry"
edition = "2021"
license = "MIT OR Apache-2.0"
name = "tauri-plugin-sentry"
readme = "README.md"
repository = "https://github.com/JonasKruckenberg/sentry-tauri"
version = "0.1.0"

[dependencies]
tauri = { git = "https://github.com/tauri-apps/tauri" }
serde = { version = "1.0", features = ["derive"] }
sentry = "0.27.0"
sentry-rust-minidump = "0.1.3"
serde_json = "1.0.85"
